### ISSUE TITLE
kselftest log and results appear to be mangled

### ISSUE THREAD

**Issue by gctucker** [kernelci/test-definitions#1]
As a follow-up from https://github.com/kernelci/kernelci-core/pull/445, there appears to be some issues with the kselftest log being mangled in the LAVA logs.  Also, the output appear to be parsed by `sed` rather than a proper TAP13 parser.  These 2 things may be related, if the mangled log output is a side effect of parsing results with `sed`.

A better approach would seem to be capturing the TAP13 results and parse it with something such as [`tappy`](https://github.com/python-tap/tappy/).  Then ideally, the output associated with each test case should be output before telling LAVA the test case name and pass/fail status.

**Comment by kees** [comment]
I think I've fixed all the problems I see with kselftests now. I've got 2 PRs pending:
https://github.com/Linaro/test-definitions/pull/207
https://github.com/Linaro/test-definitions/pull/208

**Comment by gctucker** [comment]
Right, parsing results with an inline Perl script.  Would it still not be better to use an existing implementation?  Also it's important to keep the output of each test before the test results are being reported in LAVA, so we can associate the test log fragments with each test case.

We could add these PRs to this repo and give it a try on https://staging.kernelci.org - that's what it's for.

**Comment by gctucker** [comment]
OK I've made this branch, it should get tested on staging later today (next round scheduled for 16:00 UTC):
https://github.com/kernelci/test-definitions/commits/staging.kernelci.org
